name: CitiesPlugin
version: 1.0
main: Main.CitiesPlugin
commands:
  city:
    description: The standard city command to manipulate cities.
    usage: /city <subcommand>
    permission: cities.city
permissions:
  cities.city:
    description: Allow the use of the standard city command
    default: true
    children:
      cities.city.list:
        description: List all cities
        default: true
      cities.city.info:
        description: Show info for your city
        default: true
  cities.city.admin:
    description: This permission allows editing / deleting of all cities, as well as building in them
    default: op
    children:
      cities.city.map:
        description: Permission to use the city map
        default: op
      cities.city.chunks:
        description: Permission to manipulate chunks to add or remove from your city.
        default: op
      cities.city.residents:
        description: Permission to add or remove residents from your city.
        default: op
      cities.city.delete:
        description: Permission to delete any city.
        default: op
      cities.city.create:
        description: Permission to create a city.
        default: op
      cities.city.tp:
        description: Permission to teleport to a city.
        default: op