name: CitiesPlugin
version: 1.0
main: Main.CitiesPlugin
commands:
  city:
    description: The standard city command to manipulate cities.
    usage: /city <subcommand>
    permission: cities.city
permissions:
  cities.city:
    description: Allow the use of the standard city command
    default: true
  cities.city.map:
    description: Permission to use the city map
    default: op
  cities.city.protection:
    description: Overrides the block protection in cities. Players with this permission can build, destroy and interact in every city.
    default: op