name: CitiesPlugin
version: 1.0
main: Main.CitiesPlugin
commands:
  city:
    description: The standard city command to manipulate cities.
    usage: /city <subcommand>
    permission: cities.city
permissions:
  cities.city:
    description: Allow the use of the standard city command
    default: true
    children:
      cities.city.list:
        description: List all cities
        default: true
  cities.city.admin:
    description: Overrides the block protection in cities. Players with this permission can build, destroy and interact in every city.
    default: op
    children:
      cities.city.map:
        description: Permission to use the city map
        default: op
      cities.city.chunks:
        description: Permission to manipulate chunks to add or remove from your city.
        default: op